name: Run VUnit Tests

on:
  push:
    branches:
      - main
      - test-ci
  pull_request:
  workflow_dispatch:

jobs:
  vunit-ghdl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install vunit_hdl

      - name: Install GHDL (LLVM backend)
        uses: ghdl/setup-ghdl@v1
        with:
          backend: llvm

      - name: Run VUnit tests
        run: |
              python run.py tb.tb_timer.default.reset_is_respected
              python run.py tb.tb_timer.default.start_is_ignored_while_busy
              python run.py tb.tb_timer.*.waits_the_correct_amount_of_time

  formal-verification:
    name: Run Formal Verification (SymbiYosys)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OSS CAD Suite
        run: |
          sudo apt update
          sudo apt install -y wget xz-utils
          wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-11-01/oss-cad-suite-linux-x64-20231101.tgz
          tar -xzf oss-cad-suite-linux-x64-20231101.tgz
          echo "$PWD/oss-cad-suite/bin" >> $GITHUB_PATH

      - name: Verify tool installation
        run: |
          yosys -V
          sby --version
          yosys-smtbmc --help | head -n 1

      - name: Run formal proof
        working-directory: formal
        run: |
          sby -f timer_proof.sby


